# Generated by Django 5.2.7 on 2025-11-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('free', 'Free')], db_index=True, default='free', max_length=20),
        ),
    ]
