server {
    listen 80;
    server_name yourdomain.com www.yourdomain.com;

    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ {
        root /home/hasan/akashraja;
    }

    location /media/ {
        root /home/hasan/akashraja;
    }

    # Daphne for WebSockets
    location /ws/ {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_redirect off;
        proxy_pass http://0.0.0.0:8001;
    }

    # Gunicorn for HTTP
    location / {
        include proxy_params;
        proxy_pass http://unix:/home/hasan/akashraja/akashraja.sock;
    }
}
