# Generated by Django 5.2.7 on 2025-10-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_album_albumimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimage',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='album_audios/'),
        ),
    ]
