# Generated by Django 5.2.7 on 2025-11-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamechallenge',
            name='category',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='category',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
