# Generated by Django 5.2.7 on 2025-11-18 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamechallenge_category_gamesession_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamechallenge',
            name='category',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='category',
        ),
    ]
