# Generated by Django 5.2.7 on 2025-11-19 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_gamechallenge_category_and_more'),
        ('home', '0003_albumimage_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamechallenge',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
    ]
