# Generated by Django 5.2.7 on 2025-11-19 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gamechallenge_category'),
        ('home', '0003_albumimage_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
    ]
